### ISSUE TITLE
DatasetGenerator missing

### ISSUE THREAD

**Issue by unique-null** [koriavinash1/Optic-Disk-Cup-Segmentation#1]
Hi @koriavinash1 ,

In ```Trainer.py```,  there exist ```from DatasetGenerator import DatasetGenerator```. However, there is no code named ```DatasetGenerator```, can you provided it.

Thx!

**Comment by koriavinash1** [comment]
Hi @SwagJzzZ ,

Thanks for spotting the missing file, I've made a push with DatasetGenerator ...

Thankyou
